### ISSUE TITLE
Problem with defonce and URLStreamHandlerFactory

### ISSUE THREAD

**Issue by jumarko** [jakemcc/test-refresh#84]
I've got a problem with `lein test-refresh` when using it on our project where there's a cusome URLStreamHandlerFactory defined like this: 
```
(defonce _factory
         (URL/setURLStreamHandlerFactory
           (reify
             URLStreamHandlerFactory
             (createURLStreamHandler [this protocol]
               (protocol-handlers protocol)))))
```

`defonce` is used to avoid multiple calls of setURLStreamHandlerFactory - otherwise you get this java.lang.Error
```
1. Unhandled java.lang.Error
   factory already defined

                  URL.java: 1135  java.net.URL/setURLStreamHandlerFactory
```

**What version of lein-test-refresh?**

`[com.jakemccrary/lein-test-refresh "0.25.0"]`

**What version of Leiningen?**

`Leiningen 2.9.8 on Java 1.8.0_302 OpenJDK 64-Bit Server VM`

**Can you recreate the issue with a minimal project?**

https://github.com/jumarko/lein-refresh-defonce-problem

**Comment by jakemcc** [comment]
Thanks for the issue report. This is a more general complication with writing code that can be reloaded safely and not an issue with test-refresh.
`

**Comment by jakemcc** [comment]
Hi @jumarko ,

Thanks for the detailed issue. For better or worse, this isn't a problem with test-refresh and is a more general issue with writing code that works well with using tools like test-refresh.

test-refresh uses [tools.namespace](https://github.com/clojure/tools.namespace#no-global-state) to handle the reloading. This is way more reliable than just re-requiring a namespace but does force us to take certain considerations when writing code that is safe to reload. The [Reloading Code: Preparing Your Application](https://github.com/clojure/tools.namespace#no-global-state) goes into some of these considerations.

Sometimes you can get around this by wrapping top level `def`s that have side-effects with a `delay`. This prevents the unloading and loading of the namespace from triggering the side-effect.

**Comment by jumarko** [comment]
Thanks for the answer.
I don't think I can use `delay` in this case but maybe I can make the initialization a function and call it early in the app initialization sequence.

**Comment by jakemcc** [comment]
That could work too.

Another pattern I've found is to put things-that-you-don't-want-to-be-reloaded-regularly into their own, isolated namespaces that has minimal dependencies. This basically creates a namespace that has very little reason to change so it gets reloaded very infrequently.

An example of items I isolate to their own namespaces are `defprotocol` since reloading protocols gets a little weird.

**Comment by jakemcc** [comment]
I was just reviewing some of the old issues on test-refresh and stumbled across this one that talks about disabling reloading for a particular namespace. Kind of an extreme measure and probably not as good as getting a side-effect out of a `def` but I thought it was worth linking.

https://github.com/jakemcc/test-refresh/issues/26

**Comment by metametadata** [comment]
Something to consider is migrating `test-refresh` from `tools.namespace` to https://github.com/tonsky/clj-reload because it allows keeping selected variables between reloads. Also its unload hooks could be handy to simplify fixture clean-up on reloading.
