### ISSUE TITLE
Feature Request: write out .lein-failures each loop so you can inspect current failures from a file

### ISSUE THREAD

**Issue by gleenn** [jakemcc/test-refresh#89]
*Use the template below when reporting bugs. Please make sure the
problem is still a problem with the latest version of
lein-test-refresh before submitting.*

This is a feature request, no bugs :)

**What version of lein-test-refresh?**

Latest as of now, version 0.25.0

**What version of Leiningen or Clojure (for deps.edn projects)?**

lein -v
Leiningen 2.9.8 on Java 11.0.4 OpenJDK 64-Bit Server VM

**Can you recreate the issue with a minimal project?**

Yup, every project should emit a nice .lein-failures every run but doesn't

**If you can't do above, can you share your project.clj and project structure?**
sure

**Comment by jakemcc** [comment]
Sorry for the lack of a response. Not entirely sure how I missed a notification about this, I wonder if github emails are getting marked as spam or something.

I'm not familiar with `.lein-failures` file, though looking at Leiningen's source and I can see it creates it. If it is easy and not too messy to do, I can try recreating it.

What causes you to want to look at `.lein-failures` over the normal test output? If it is just an annoying amount of printing to the console, test-refresh has the [:quiet](https://github.com/jakemcc/test-refresh/blob/master/sample.project.clj#L24) option which I'd recommend turning on.

**Comment by jakemcc** [comment]
I took a look at what Leiningen is doing and don't really want to hook any more into clojure.test than test-refresh already does. Probably not going to do this work without getting more justification around the use of `.lein-failures`. 

I'm finding it hard to get motivated to do the work and ongoing maintenance for a file I wasn't aware of and hadn't heard of other Clojure devs caring about it. But open to hearing more about it.
